version: 0.0.1-b{build}
image: Visual Studio 2017
before_build:
- ps: nuget restore
build:
  project: Bud.Builder.sln
  verbosity: minimal
before_package:
  - ps: 'cd Bud.Builder; nuget pack Bud.Builder.csproj'
artifacts:
  - path: Bud.Builder/bin/Debug/Bud.Builder.dll
    name: Bud.Builder.dll
  - path: Bud.Builder/bin/Debug/Bud.Builder.xml
    name: Bud.Builder.xml
  - path: 'Bud.Builder/*.nupkg'
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
deploy: off
