version: 1.0.0-b{build}
image: Visual Studio 2017
before_build:
- ps: nuget restore
build:
  project: Bud.Building.sln
  verbosity: minimal
deploy: off
artifacts:
  - path: Bud.BuildEngine/bin/Debug/Bud.BuildEngine.dll
    name: Bud.BuildEngine.dll
  - path: Bud.BuildEngine/bin/Debug/Bud.BuildEngine.xml
    name: Bud.BuildEngine.xml
  - path: 'Bud.BuildEngine/*.nupkg'
assembly_info:
  patch: true
  file: Bud.BuildEngine/Properties/AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
assembly_info:
  patch: true
  file: Bud.Building/Properties/AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'