version: 1.0.0-b{build}
image: Visual Studio 2017
before_build:
- ps: nuget restore
build:
  project: Bud.Building.sln
  verbosity: minimal
deploy: off
assembly_info:
  patch: true
  file: */Properties/AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'